spring:
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/staffRestaurant?serverTimezone=UTC&characterEncoding=UTF-8
    username: staffAdmin
    password: 1234
    connection-timeout: 5000 #클라이언트가 pool에 connection을 요청하는데 기다리는 최대시간을 설정합니다.
    validation-timeout: 1000
    maximum-pool-size: 10    #유휴 및 사용중인 connection을 포함하여 풀에 보관가능한 최대 커넥션 개수를 설정합니다.
    connection-test-query: SELECT 1 #데이터베이스 연결이 여전히 활성화되어있는지 확인하기 위해 pool에서 connection을 제공하기 전에 실행되는 쿼리입니다.

mybatis:
  type-aliases-package: com.staffRestaurant.*.mapper.*
  mapper-locations: classpath*:mybatis/mapper/*.xml

  
logging:
   level:
      root: info